// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type ExampleType1 struct {
	ID          *string `json:"id" bson:"_id"`
	Name        *string `json:"name"`
	Description *string `json:"description" bson:"omitempty"`
}

type ExampleType2 struct {
	ID          *string `json:"id" bson:"_id"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Something   *string `json:"something" bson:"omitempty"`
}
